MLlib/models.py
MLlib/optimizers.py
MLlib/utils.py
example.py

Nesterov Accelerated Gradient Descent.
Adagrad
Adadelta
Adam

Added Gradient Descent Algos

---

PULL_REQUEST_TEMPLATE.md

added PR template for better description.

Added PULL REQUEST TEMPLATE

---

linear_example.py
logistic_example.py

Changed learning rate of Adam to improve learning in Linear Regression example.
Separated examples of Logistic Regression and Linear Regression.

Added examples for 2 models (Enhancement)

---

MLlib/__init__.py
MLlib/utils/__init__.py
setup.py

--
Added `setup.py` and `__init__.py` for packaging the repo.
To install this repo use `python3 setup.py install`
--

Added setup.py and__init__.py for packaging

---

.gitignore

vscode ignore

---

MLlib/activations.py

Few more activation functions like Tanh, ReLU, Softmax, Leaky ReLU, Softsign, and ELU have been added in the activations.py file
Please merge it if found useful

Added a few more Activations

---

README.md

Updated Readme Section

---

MLlib/models.py
MLlib/utils/knn_utils.py

KNN Docstring Update

---

MLlib/models.py
MLlib/utils/gaussian_naive_bayes_utils.py
MLlib/utils/naive_bayes_utils.py

added docstrings for naives bayes, GNB

---

MLlib/activations.py

Fixes #60 
Created Sigmoid class with activation and derivative methods. The derivative method returns the derivative of sigmoid of the vector X.

Added derrivative of sigmoid

---

MLlib/activations.py

Fixes #60 
Created TanH class with activation and derivative methods. The derivative method returns the array of derivatives of hyperbolic tangent function on X Vector.

Added derivative of tanh

---

MLlib/activations.py

Fixes #60 
Created Relu class with activation and derivative methods. The derivative method returns the array of derivatives of Rectified Linear Unit on X Vector.

Added derivative of Relu

---

CODE_OF_CONDUCT.md

The issue fixes #82 which is a formal code of Conduct

Create CODE_OF_CONDUCT.md issue #82

---

MLlib/activations.py

This PR corresponds to issue #69. Added functions are Binary step function and Swish activation function.

Two activation functions added

---

MLlib/activations.py

Fixes #60 
Created LeakyRelu class with activation and derivative methods. The derivative method returns the array of derivatives of the applied Leaky Rectified Linear Units on X Vector.

Added derivative of leaky Relu

---

MLlib/tests/test_activations.py

Added one test function for Relu Class

---

MLlib/utils/misc_utils.py

Implemented the One hot encoding class.
Fixes #41
FUNCTIONS in OneHotEncoder class are:
(1) FIT(INPUT_X, THRESHOLD) --- It is used to calculate the number of unique values in each column and tell whether a particular column should be encoded or not.
(2) CHECK_TRANSFORM(INPUT_X) --- It is used to check whether the data which is being transformed has the same values as the data which was used to fit it.
(3) TRANSFORM(INPUT_X) --- It is used to OneHotEncode the data based on the data which was used to fit
(4) FIT_TRANSFORM(INPUT_X, THRESHOLD) --- This function is just a combination of the fit and the transform function.
INPUTS in OneHotEncoder are:
X - It is a NumPy array of size n x m.
thresh - It is a threshold value which is calculated as THRESH = (NUMBER OF UNIQUE VALUES IN A …

Implement One hot encoding 

---

MLlib/activations.py
MLlib/tests/test_activations.py

This PR corresponds to issue #99. Fixed the implementation of unit step function.

Fixed the unit step function

---

README.md

--
Added updates to readme for using tests
--

Update readme to add tests

---

Examples/multinomial_naive_bayes_example.py
Examples/naive_bayes_example.py

removed slashes

---

MLlib/loss_func.py

Added cosine similarity function

---

MLlib/loss_func.py

PEP8 Fixes

---

MLlib/models.py

Mistakenly Deleted, while merging PR for Decision Tree and Random Forest.

Restore Numerical_Outlier Method Class

---

MLlib/loss_func.py

Added Huber loss function.

---

Examples/linear_example.py
MLlib/models.py

fixes #66 
create a function plot 
plot linear regression loss vs epochs 2-D graph

Plot Linear regression Loss vs epochs 2-D graph

---

Examples/Polynomial_example.py
MLlib/models.py

Implemented graphs for Polynomial Model

---

Examples/bayes_optimization_example.py
MLlib/models.py

Fixes #65 
Implemented the bayes optimization taking a gaussian process regressor as a surrogate function for representative purposes.

Implemented Bayes Optimization

---

Examples/agglomerative_clustering_example.py

changed the argument value in agglomerative example file

---

MLlib/activations.py

#151 introduced a wrong implementation of softmax function's derivative in the backward pass. This is fixed now.
reference: https://stackoverflow.com/questions/36279904/softmax-derivative-in-numpy-approaches-0-implementation

Fixed Softmax function's backward pass

---

Examples/regularizer_example.py
MLlib/regularizer.py

Implemented L1(Lasso) and L2(Ridge) Regularizer

---

MLlib/utils/divisive_clustering_utils.py

Trying to solve version compatibility issue

Vinit: 'color' to 'c' at some places

---

Examples/linear_example.py
Examples/preprocess_example.py
MLlib/models.py

implement scatter plot and line plot.
changes in example files

Implement More graphs and  changes in example file

---

MLlib/loss_func.py

Removed error in cosine similarity

---

MLlib/loss_func.py

Removed error in Huber loss function

---

MLlib/loss_func.py
README.md
setup.py

1. Added Mean Absolute Percentage Error Function
2. Made Changes in Readme after this addition.
Future Goal :- 
1. Add Derivative for Mean Absolute Percentage Error.

Added Mean Absolute Percentage Error

---

.github/workflows/python-app.yml

NA
+ Added `python-app.yml` for lint testing using flake8.
Currently, `python-app.yml` file is configured to install dependencies as well which are not used in lint testing but will be used later for pytest.

Initialized GitHub Action (lint test)

---

MLlib/tests/test_activations.py
MLlib/tests/test_demo.py

NA
Removed test_demo.py from MLlib/tests
Added test_activations.py in MLlib/tests, which contains a unit test for Sigmoid Activation.

Added unit test for Sigmoid Activation

---

MLlib/tests/test_activations.py

Unit test for TanH added

---

.github/workflows/python-app.yml
Examples/k_means_clustering_example.py
Examples/knn_classification_example..py
Examples/knn_example.py
MLlib/distance_metrics.py
MLlib/models.py
MLlib/tests/test_activations.py

NA
+ Resolved all flake8 lint warnings.
+ Increased code complexity allowance in flake8 from 10 to 12.
+ flake8 detections are no longer warnings. Instead, they will be treated as errors now.

Resolved flake8 issues

---

.github/workflows/python-app.yml
MLlib/tests/test_activations.py

Adds Softmax unit test to test_demo.py

Unit test for Softmax
